default: &default
  adapter: mysql2
  encoding: utf8
  username: vagrant
  host: 127.0.0.1
  port: 3306
  pool: 5

development:
  <<: *default
  database: file_importer

test:
  <<: *default
  database: file_importer_test
